name: env_submission
channels:
  - defaults
dependencies:
  - python=3.12.7  # Sesuaikan ke versi ini
  - pip
  - pip:
    - mlflow==2.19.0
    - scikit-learn
    - pandas
    - matplotlib
    - dagshub